float64 x #target x position
float64 y #target y position
float64 z #target z position
float64 roll #target roll
float64 pitch
float64 yaw
---
#result
bool success
string message
---
#feedback
float64 distance_translation #distance between feedback and target translation
float64 distance_orientation #shortest angle between feedback and orientation
float64 time_elapsed #time elapsed since action request is accepted

